version: "3.9" 

services:
  machine:
    build: 
      context: ./nestjs
      # dockerfile: machine.dockerfile
      target: development
    platform: linux/amd64
    ports: 
      - 4000:4000
      - 9229:9229
    volumes:
      - ./api/src/:/usr/api/machine/src
      - ./package.json:/usr/api/machine/package.json
      - ~/.config/gcloud:/home/node/.config/gcloud
    environment:
      ENVIRONMENT: local
    env_file:
      - api/.env
    depends_on:
      - neo4j
    command: npm run install:start:dev

  neo4j:
    image: neo4j:latest
    ports:
      - 7474:7474
    volumes:
      - ./neo4j:/data
    environment:
      NEO4J_AUTH: neo4j/password
