version: "3.9" 

services:
  neo4j:
    image: neo4j:latest
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - ./neo4j/data:/var/lib/neo4j/data
      - ./neo4j/import:/var/lib/neo4j/import
      - ./neo4j/logs:/var/lib/neo4j/logs
    environment:
      NEO4J_AUTH: neo4j/password
      NEO4J_PLUGINS: "[\"apoc\"]"
      NEO4J_apoc_export_file_enabled: true
      NEO4J_apoc_import_file_enabled: true
      NEO4J_apoc_import_file_use__neo4j__config: true

  machine-graph:
    build: 
      dockerfile: ./api/machine.Dockerfile
    platform: linux/amd64
    volumes:
      - ./api/src:/home/node/app/src
      - ~/.config/gcloud:/home/node/.config/gcloud
    env_file:
      - ./api/.env
    ports:
      - 4000:4000
      - 9229:9229
    command: ["npm", "run", "start:debug"]
    depends_on:
      - neo4j
