version: "3.9" 

services:
  neo4j:
    image: neo4j:latest
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - ./neo4j/data:/var/lib/neo4j/data
      - ./neo4j/import:/var/lib/neo4j/import
      - ./neo4j/logs:/var/lib/neo4j/logs
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:7474/", "||", "exit 1"] 
      interval: 10s
      timeout: 2s
      retries: 10
    environment:
      NEO4J_AUTH: neo4j/password
      NEO4J_PLUGINS: "[\"apoc\"]"
      NEO4J_apoc_export_file_enabled: true
      NEO4J_apoc_import_file_enabled: true
      NEO4J_apoc_import_file_use__neo4j__config: true

  machine-graph:
    build: 
      context: ./api
      dockerfile: ./machine.Dockerfile
      target: development
    platform: linux/amd64
    ports: 
      - 4000:4000
      - 9229:9229
    volumes:
      - ./dist/:/usr/app/src
      - ./api/.env:/usr/app/src.env
      - ~/.config/gcloud:/home/node/.config/gcloud
    env_file:
      - ./api/.env
    depends_on:
      - neo4j
